export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_SINGLE_PRODUCT_START = "GET_SINGLE_PRODUCT_START";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const SET_GRIDVIEW = "SET_GRIDVIEW";
export const SET_LISTVIEW = "SET_LISTVIEW";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const INCREASE_DECREASE_TOGGLE = "INCREASE_DECREASE_TOGGLE";
export const UPDATE_SORT = "UPDATE_SORT";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const   GET_PRODUCT_REVIEW_START = "GET_PRODUCT_REVIEW_START"
export const GET_PRODUCT_REVIEW_SUCCESS = "GET_PRODUCT_REVIEW_SUCCESS";
export const GET_PRODUCT_REVIEW_ERROR = "GET_PRODUCT_REVIEW_ERROR";







