// export const SIDEBAR_OPEN = 'SIDEABAR_OPEN'
// export const SIDEBAR_CLOSE = "SIDEABAR_CLOSE";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";


